### ISSUE TITLE
Handle the api response where "finish_state" or choices is missing

### ISSUE THREAD

**Issue by jordibruin** [heysaik/ChatGPTKit#3]
Sometimes the API doesn't return these things and then the decoding fails.

This repo has been super helpful, thanks 🙂

**Comment by heysaik** [comment]
Fixed!
- Set the `choices` parameter to `Optional<[ResponseChoice]>`
- Set the `finish_reason` parameter to `Optional<String>`
- Also implemented to `APIError` and `ErrorResponse` types to better handle error returned from the OpenAI API. This should offer more insight into why certain API calls might fail. More info in the [README](../blob/main/README.md).

Thanks Jordi!

**Comment by jordibruin** [comment]
You're the best!
